// frontend/src/App.jsx
import { useState, useRef, useEffect } from 'react'

function App() {
  const [messages, setMessages] = useState([
    { 
      role: 'assistant', 
      content: 'Hello! I am your database assistant. How can I help you today?',
      logs: [],
      isComplete: true
      // No id here: ensures greeting renders as simple text
    }
  ])
  const [input, setInput] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const messagesEndRef = useRef(null)

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" })
  }

  useEffect(() => {
    scrollToBottom()
  }, [messages])

  const handleSendMessage = async (e) => {
    e.preventDefault()
    if (!input.trim()) return

    const userMessage = { role: 'user', content: input }
    setMessages(prev => [...prev, userMessage])
    setInput('')
    setIsLoading(true)

    // Add a placeholder assistant message with a unique ID
    const assistantMessageId = Date.now()
    setMessages(prev => [
      ...prev, 
      { 
        id: assistantMessageId,
        role: 'assistant', 
        logs: [], 
        content: '', 
        isComplete: false 
      }
    ])

    try {
      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ message: input }),
      })

      if (!response.body) throw new Error('ReadableStream not supported')

      const reader = response.body.getReader()
      const decoder = new TextDecoder()
      let buffer = ''

      while (true) {
        const { done, value } = await reader.read()
        if (done) break

        buffer += decoder.decode(value, { stream: true })
        const lines = buffer.split('\n')
        buffer = lines.pop() || '' 

        for (const line of lines) {
          if (!line.trim()) continue
          try {
            const data = JSON.parse(line)
            
            setMessages(prev => prev.map(msg => {
              if (msg.id !== assistantMessageId) return msg
              
              if (data.type === 'log') {
                return { ...msg, logs: [...msg.logs, data.content] }
              } else if (data.type === 'result') {
                return { ...msg, content: data.content, isComplete: true }
              } else if (data.type === 'error') {
                 return { ...msg, content: `Error: ${data.content}`, isComplete: true }
              }
              return msg
            }))

          } catch (e) {
            console.error('Error parsing JSON line:', e)
          }
        }
      }
    } catch (error) {
      console.error('Error sending message:', error)
      setMessages(prev => prev.map(msg => {
         if (msg.id !== assistantMessageId) return msg
         return { ...msg, content: 'Sorry, I encountered an error connecting to the server.', isComplete: true }
      }))
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="flex flex-col h-screen w-screen bg-gray-50 text-gray-800 font-sans">
      {/* Header */}
      <header className="bg-white p-4 shadow-sm border-b border-gray-200 sticky top-0 z-10">
        <h1 className="text-xl font-semibold text-gray-700">LangGraph DB Chatbot</h1>
      </header>

      {/* Messages Area */}
      <main className="flex-1 overflow-y-auto p-4 space-y-6">
        {messages.map((msg, index) => (
          <div
            key={index}
            className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
          >
            <div
              className={`max-w-[90%] md:max-w-[80%] rounded-lg p-4 shadow-sm ${
                msg.role === 'user'
                  ? 'bg-blue-50 text-gray-800 border border-blue-100'
                  : 'bg-white text-gray-800 border border-gray-200 w-full'
              }`}
            >
              {msg.role === 'assistant' ? (
                <AssistantMessageContent message={msg} />
              ) : (
                <p className="whitespace-pre-wrap">{msg.content}</p>
              )}
            </div>
          </div>
        ))}
        {isLoading && (
           <div className="flex justify-start opacity-50">
             <span className="text-sm text-gray-500 ml-2 animate-pulse">Processing...</span>
           </div>
        )}
        <div ref={messagesEndRef} />
      </main>

      {/* Input Area */}
      <footer className="p-4 bg-white border-t border-gray-200 sticky bottom-0 z-10">
        <form onSubmit={handleSendMessage} className="flex space-x-2 max-w-4xl mx-auto">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Ask about your data..."
            className="flex-1 bg-gray-50 text-gray-800 border border-gray-300 rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:border-transparent transition-shadow shadow-inner"
            disabled={isLoading}
          />
          <button
            type="submit"
            disabled={isLoading || !input.trim()}
            className="bg-blue-600 hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed text-white font-medium py-3 px-6 rounded-lg transition-colors shadow-sm"
          >
            Send
          </button>
        </form>
      </footer>
    </div>
  )
}

function AssistantMessageContent({ message }) {
  const [activeTab, setActiveTab] = useState('processing')
  const [hasAutoSwitched, setHasAutoSwitched] = useState(false)
  
  // Auto-switch to Output tab ONLY once when complete and content exists
  useEffect(() => {
    if (message.isComplete && message.content && !hasAutoSwitched) {
      setActiveTab('output')
      setHasAutoSwitched(true)
    }
  }, [message.isComplete, message.content, hasAutoSwitched])

  // Simple rendering for messages without an ID (like the initial greeting)
  if (!message.id) {
      return <p className="whitespace-pre-wrap">{message.content}</p>
  }

  return (
    <div className="flex flex-col w-full h-full">
      {/* Tabs */}
      <div className="flex border-b border-gray-200 mb-3">
        <button
          onClick={() => setActiveTab('processing')}
          className={`px-4 py-2 text-sm font-medium transition-colors ${
            activeTab === 'processing'
              ? 'text-blue-600 border-b-2 border-blue-600'
              : 'text-gray-500 hover:text-gray-700'
          }`}
        >
          Query Processing
        </button>
        <button
          onClick={() => setActiveTab('output')}
          className={`px-4 py-2 text-sm font-medium transition-colors ${
            activeTab === 'output'
              ? 'text-blue-600 border-b-2 border-blue-600'
              : 'text-gray-500 hover:text-gray-700'
          }`}
        >
          Output
        </button>
      </div>

      {/* Content */}
      <div className="flex-1 min-h-[120px]">
        {activeTab === 'processing' ? (
          <div className="bg-gray-50 p-3 rounded-md font-mono text-[11px] text-gray-600 h-full overflow-x-auto max-h-[400px] overflow-y-auto border border-gray-100 shadow-inner">
            {message.logs && message.logs.length > 0 ? (
              message.logs.map((log, i) => (
                <div key={i} className="mb-1 border-b border-gray-100 pb-1 last:border-0 last:pb-0">
                  {log}
                </div>
              ))
            ) : (
              <div className="flex items-center space-x-2">
                <div className="w-2 h-2 bg-blue-400 rounded-full animate-ping"></div>
                <span className="italic text-gray-400">Waiting for process logs...</span>
              </div>
            )}
             {/* Auto-scroll to bottom of logs inside the tab */}
             <div ref={(el) => el?.scrollIntoView({ behavior: "smooth" })} />
          </div>
        ) : (
          <div className="prose prose-sm max-w-none text-gray-800 animate-in fade-in duration-500">
            {message.content ? (
              <p className="whitespace-pre-wrap">{message.content}</p>
            ) : (
              <div className="flex flex-col items-center justify-center h-24 text-gray-400 italic space-y-2">
                <div className="flex space-x-1">
                  <div className="w-1.5 h-1.5 bg-gray-300 rounded-full animate-bounce"></div>
                  <div className="w-1.5 h-1.5 bg-gray-300 rounded-full animate-bounce [animation-delay:-.15s]"></div>
                  <div className="w-1.5 h-1.5 bg-gray-300 rounded-full animate-bounce [animation-delay:-.3s]"></div>
                </div>
                <span>Processing final answer...</span>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  )
}

export default App

// frontend/src/App.vue
<script setup>
import { ref, onMounted, nextTick, watch } from 'vue'

const messages = ref([
  { 
    role: 'assistant', 
    content: 'Hello! I am your database assistant. How can I help you today?',
    logs: [],
    isComplete: true
  }
])
const input = ref('')
const isLoading = ref(false)
const messagesEndRef = ref(null)

const scrollToBottom = async () => {
  await nextTick()
  if (messagesEndRef.value) {
    messagesEndRef.value.scrollIntoView({ behavior: "smooth" })
  }
}

watch(messages, () => {
  scrollToBottom()
}, { deep: true })

const handleSendMessage = async () => {
  if (!input.value.trim()) return

  const userMessage = { role: 'user', content: input.value }
  messages.value.push(userMessage)
  
  const currentInput = input.value
  input.value = ''
  isLoading.value = true

  const assistantMessageId = Date.now()
  const newMessage = { 
    id: assistantMessageId,
    role: 'assistant', 
    logs: [], 
    content: '', 
    isComplete: false,
    activeTab: 'processing',
    hasAutoSwitched: false
  }
  messages.value.push(newMessage)

  try {
    const response = await fetch('/api/chat', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ message: currentInput }),
    })

    if (!response.body) throw new Error('ReadableStream not supported')

    const reader = response.body.getReader()
    const decoder = new TextDecoder()
    let buffer = ''

    while (true) {
      const { done, value } = await reader.read()
      if (done) break

      buffer += decoder.decode(value, { stream: true })
      const lines = buffer.split('\n')
      buffer = lines.pop() || '' 

      for (const line of lines) {
        if (!line.trim()) continue
        try {
          const data = JSON.parse(line)
          
          const msgIndex = messages.value.findIndex(m => m.id === assistantMessageId)
          if (msgIndex !== -1) {
            const msg = messages.value[msgIndex]
            if (data.type === 'log') {
              msg.logs.push(data.content)
            } else if (data.type === 'result') {
              msg.content = data.content
              msg.isComplete = true
              // Auto-switch tab
              if (!msg.hasAutoSwitched) {
                msg.activeTab = 'output'
                msg.hasAutoSwitched = true
              }
            } else if (data.type === 'error') {
              msg.content = `Error: ${data.content}`
              msg.isComplete = true
              msg.activeTab = 'output'
            }
          }
        } catch (e) {
          console.error('Error parsing JSON line:', e)
        }
      }
    }
  } catch (error) {
    console.error('Error sending message:', error)
    const msgIndex = messages.value.findIndex(m => m.id === assistantMessageId)
    if (msgIndex !== -1) {
      messages.value[msgIndex].content = 'Sorry, I encountered an error connecting to the server.'
      messages.value[msgIndex].isComplete = true
      messages.value[msgIndex].activeTab = 'output'
    }
  } finally {
    isLoading.value = false
  }
}
</script>

<template>
  <div class="app-container">
    <header class="header">
      <h1>LangGraph DB Chatbot (Vue)</h1>
    </header>

    <main class="messages-area">
      <div v-for="(msg, index) in messages" :key="index" :class="['message-wrapper', msg.role]">
        <div :class="['message-bubble', msg.role]">
          <!-- USER MESSAGE -->
          <template v-if="msg.role === 'user'">
            <p class="content-text">{{ msg.content }}</p>
          </template>

          <!-- ASSISTANT MESSAGE -->
          <template v-else>
            <div class="assistant-content">
              <!-- Initial Greeting (no tabs) -->
              <div v-if="!msg.id">
                <p class="content-text">{{ msg.content }}</p>
              </div>

              <!-- Chat Responses (with tabs) -->
              <div v-else class="tabbed-container">
                <div class="tabs-header">
                  <button 
                    @click="msg.activeTab = 'processing'" 
                    :class="{ active: msg.activeTab === 'processing' }"
                    class="tab-btn"
                  >
                    Query Processing
                  </button>
                  <button 
                    @click="msg.activeTab = 'output'" 
                    :class="{ active: msg.activeTab === 'output' }"
                    class="tab-btn"
                  >
                    Output
                  </button>
                </div>
                
                <div class="tab-content">
                  <!-- Processing Logs Tab -->
                  <div v-if="msg.activeTab === 'processing'" class="logs-container">
                    <div v-if="msg.logs.length > 0" class="logs-list">
                      <div v-for="(log, i) in msg.logs" :key="i" class="log-entry">
                        {{ log }}
                      </div>
                    </div>
                    <div v-else class="waiting-logs">
                      <div class="ping-dot"></div>
                      <span>Waiting for process logs...</span>
                    </div>
                  </div>
                  
                  <!-- Final Output Tab -->
                  <div v-else class="output-container">
                    <p v-if="msg.content" class="content-text">{{ msg.content }}</p>
                    <div v-else class="processing-placeholder">
                      <div class="bounce-dots">
                        <span>.</span><span>.</span><span>.</span>
                      </div>
                      <span>Processing final answer...</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </template>
        </div>
      </div>
      <div v-if="isLoading" class="loading-indicator">
        <span class="processing-text">Processing...</span>
      </div>
      <div ref="messagesEndRef"></div>
    </main>

    <footer class="footer">
      <form @submit.prevent="handleSendMessage" class="input-form">
        <input
          v-model="input"
          type="text"
          placeholder="Ask about your data..."
          class="chat-input"
          :disabled="isLoading"
        />
        <button
          type="submit"
          :disabled="isLoading || !input.trim()"
          class="send-button"
        >
          Send
        </button>
      </form>
    </footer>
  </div>
</template>

<style>
/* Global styles */
:root {
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  line-height: 1.5;
  background-color: #f9fafb;
  color: #1f2937;
}
body { margin: 0; }
</style>

<style scoped>
.app-container {
  display: flex;
  flex-direction: column;
  height: 100vh;
  width: 100vw;
  background-color: #f9fafb;
}

.header {
  background: white;
  padding: 1rem;
  box-shadow: 0 1px 2px rgba(0,0,0,0.05);
  border-bottom: 1px solid #e5e7eb;
}
.header h1 {
  margin: 0;
  font-size: 1.25rem;
  color: #374151;
  font-weight: 600;
}

.messages-area {
  flex: 1;
  overflow-y: auto;
  padding: 1.5rem;
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.message-wrapper {
  display: flex;
  width: 100%;
}
.message-wrapper.user { justify-content: flex-end; }
.message-wrapper.assistant { justify-content: flex-start; }

.message-bubble {
  max-width: 85%;
  padding: 1rem;
  border-radius: 0.75rem;
  box-shadow: 0 1px 3px rgba(0,0,0,0.1);
  font-size: 0.95rem;
}
.message-bubble.user {
  background-color: #eff6ff;
  border: 1px solid #dbeafe;
  color: #1e40af;
}
.message-bubble.assistant {
  background-color: white;
  border: 1px solid #e5e7eb;
  color: #374151;
  width: 100%;
}

.assistant-content {
  width: 100%;
}

.content-text {
  white-space: pre-wrap;
  margin: 0;
}

.loading-indicator {
  display: flex;
  justify-content: flex-start;
  padding-left: 0.5rem;
}
.processing-text {
  font-size: 0.875rem;
  color: #9ca3af;
  animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
}

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: .5; }
}

.footer {
  background: white;
  padding: 1.25rem;
  border-top: 1px solid #e5e7eb;
}
.input-form {
  max-width: 56rem;
  margin: 0 auto;
  display: flex;
  gap: 0.75rem;
}

.chat-input {
  flex: 1;
  background-color: #f9fafb;
  border: 1px solid #d1d5db;
  border-radius: 0.5rem;
  padding: 0.75rem 1rem;
  outline: none;
  transition: border-color 0.2s, box-shadow 0.2s;
}
.chat-input:focus {
  border-color: #3b82f6;
  box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
}

.send-button {
  background-color: #2563eb;
  color: white;
  padding: 0.75rem 1.5rem;
  border-radius: 0.5rem;
  border: none;
  cursor: pointer;
  font-weight: 600;
  transition: background-color 0.2s;
}
.send-button:hover:not(:disabled) {
  background-color: #1d4ed8;
}
.send-button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

/* Tabbed Container Styles */
.tabbed-container {
  display: flex;
  flex-direction: column;
}
.tabs-header {
  display: flex;
  border-bottom: 1px solid #e5e7eb;
  margin-bottom: 1rem;
}
.tab-btn {
  padding: 0.625rem 1.25rem;
  font-size: 0.875rem;
  background: none;
  border: none;
  border-bottom: 2px solid transparent;
  cursor: pointer;
  color: #6b7280;
  font-weight: 500;
  transition: color 0.2s, border-color 0.2s;
}
.tab-btn:hover {
  color: #374151;
}
.tab-btn.active {
  color: #2563eb;
  border-bottom-color: #2563eb;
}

.tab-content {
  min-height: 120px;
}

.logs-container {
  background-color: #f3f4f6;
  padding: 1rem;
  border-radius: 0.5rem;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
  font-size: 0.75rem;
  color: #4b5563;
  max-height: 350px;
  overflow-y: auto;
  border: 1px solid #e5e7eb;
  box-shadow: inset 0 1px 2px rgba(0,0,0,0.05);
}
.log-entry {
  margin-bottom: 0.375rem;
  border-bottom: 1px solid #e5e7eb;
  padding-bottom: 0.375rem;
  line-height: 1.4;
}
.log-entry:last-child {
  border-bottom: none;
  margin-bottom: 0;
  padding-bottom: 0;
}

.waiting-logs {
  display: flex;
  align-items: center;
  gap: 0.625rem;
  color: #9ca3af;
  font-style: italic;
  justify-content: center;
  height: 80px;
}
.ping-dot {
  width: 0.5rem;
  height: 0.5rem;
  background-color: #3b82f6;
  border-radius: 9999px;
  position: relative;
}
.ping-dot::after {
  content: "";
  position: absolute;
  width: 100%;
  height: 100%;
  background-color: inherit;
  border-radius: inherit;
  animation: ping 1.5s cubic-bezier(0, 0, 0.2, 1) infinite;
}

@keyframes ping {
  75%, 100% { transform: scale(2.5); opacity: 0; }
}

.output-container {
  animation: fadeIn 0.3s ease-out;
}

@keyframes fadeIn {
  from { opacity: 0; transform: translateY(5px); }
  to { opacity: 1; transform: translateY(0); }
}

.processing-placeholder {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100px;
  color: #9ca3af;
  font-style: italic;
  gap: 0.5rem;
}

.bounce-dots {
  display: flex;
  gap: 0.25rem;
}
.bounce-dots span {
  width: 0.4rem;
  height: 0.4rem;
  background-color: #d1d5db;
  border-radius: 50%;
  animation: bounce 1.4s infinite ease-in-out both;
}
.bounce-dots span:nth-child(1) { animation-delay: -0.32s; }
.bounce-dots span:nth-child(2) { animation-delay: -0.16s; }

@keyframes bounce {
  0%, 80%, 100% { transform: scale(0); }
  40% { transform: scale(1.0); }
}
</style>
